### ISSUE TITLE
Weird output for v3.2.19/v4.0.9 in Rakefile

### ISSUE THREAD

**Issue by olivierlacan** [jswanner/RailsDiff#10]
![image](https://cloud.githubusercontent.com/assets/65950/4098191/6986ebe6-3009-11e4-9cf9-e9039d8bd232.png)

Not sure what that is: http://railsdiff.org/diff/v3.2.19/v4.0.9/full/#Rakefile

**Comment by jswanner** [comment]
There used to be a [shebang](http://en.wikipedia.org/wiki/Shebang_%28Unix%29) at the top of the generated Rakefile (`#!/usr/bin/env rake`), but was removed in 4.0.

You can see the difference in the source: [3.2.19](https://github.com/rails/rails/blob/v3.2.19/railties/lib/rails/generators/rails/app/templates/Rakefile) vs [4.0.0](https://github.com/rails/rails/blob/v4.0.0/railties/lib/rails/generators/rails/app/templates/Rakefile).

**Comment by jswanner** [comment]
I can understand why they'd want to remove it, in order to take advantage of the shebang: you'd need to make your Rakefile executable, and then run the Rakefile instead of `rake`.

``` bash
$ chmod +x Rakefile
$ ./Rakefile db:migrate
```

**Comment by olivierlacan** [comment]
Weird, that's not what I remember being the weird output. Oh well. :-)

**Comment by guilhermesimoes** [comment]
Isn't the issue the last line of the diff?

```
Binary files v3.2.19/app/assets/images/rails.png and v4.0.9/app/assets/images/rails.png differ
```

It definitely shouldn't appear in the Rakefile.

**Comment by jswanner** [comment]
> Isn't the issue the last line of the diff?

Ah, yes, that is an issue. I'm currently leaning towards just ignoring `*.png` files when I run `diff`, as I don't think that knowing the image changed is all that useful.

**Comment by guilhermesimoes** [comment]
When I saw this issue for the first time I also thought the shebang was the problem. Weird how the highlighting can make us blind to all the rest.

**Comment by jswanner** [comment]
I guess I should have referenced this issue in the commit messages, or made a PR out of this. Anyway, changes to the `Rakefile` were make in 71815a2bc4, and the diffs were updated in 523fa3148c.
