### ISSUE TITLE
Release candidates & betas

### ISSUE THREAD

**Issue by elsurudo** [jswanner/RailsDiff#11]
What happened to them? All I see on http://railsdiff.org are the full point releases

**Comment by caike** [comment]
Looks like https://github.com/jswanner/RailsDiff/blob/gh-pages/json/versions.json needs an update.

**Comment by olivierlacan** [comment]
I think @jswanner wanted to avoid the huge weight that would be added with all the alphas, betas, and RCs. 

Could be wrong, but realize that this would add a _lot_ of versions.

**Comment by jswanner** [comment]
@elsurudo, so the answer is a bit complicated, and something I waiver on. Generally speaking, prerelease versions (betas & release candidates) are skipped unless they are the most recent version. And, the biggest reason for it comes down to a desire to reduce file disk size -- http://railsdiff.org is a static site that is built from Rake tasks and deployed to GitHub Pages. The site currently takes up over 5GB of  my hard drive, and including all of the betas and RCs would make things much worse.

That said, there are actually many diffs that are generated and are available to view, but are not presented in the dropdown menus (http://railsdiff.org/diff/v4.1.8/v4.1.9.rc1/ for instance). I never remove a diff once it has been generated, but only display prerelease candidates if they are the latest version.

**Comment by jswanner** [comment]
> but only display prerelease candidates if they are the latest version

This is where things get a bit more complicated. If Rails released a `4.2.1.rc1` or `4.3.0.rc1` version right now you'd see it on the site. But, my previously mentioned `4.1.9.rc1` doesn't show up in the dropdown, and that's because even though that's the latest version of the `4.1.x` releases, it's not the latest version overall (which is `4.2.0`).

When `4.1.9.rc1` was released, I thought about changing this behavior so that you would see `4.1.9.rc1` as an option to compare to `4.1.8`, but I didn't make this change partly because it's not a tiny change to make and partly out of disk space concerns.

**Comment by jswanner** [comment]
All of that being said, and as I touched on before, all of this isn't set in stone. If people have strong feelings that prerelease candidates should be included, and always presented in the menu dropdowns, I could be so convinced.

**Comment by elsurudo** [comment]
I would argue that they definitely should definitely be included, as it's useful for those (like myself) that follow the latest releases whenever possible. Right now I'm on 4.2.0.rc2 and looking to upgrade to 4.2.0 proper, for example.

I must say, it's surprising to hear how large the project is on disk – I guess all those permutations add up.

**Comment by jswanner** [comment]
Well, here's the particular diff you are interested in: http://railsdiff.org/diff/v4.2.0.rc2/v4.2.0/

I'm still on the fence about always including all prerelease versions.

@olivierlacan & @caike: do you have any opinions on this?

**Comment by elsurudo** [comment]
This seems to be the only project of its type, so if we can't find those diffs here, where will we find them? :)

Thanks for the diff, btw. I've been using RailsDiff to upgrade for a long time now – love the idea.

**Comment by caike** [comment]
I can see it being very useful for release candidates to be displayed in the dropdown menu.

**Comment by jswanner** [comment]
I've completely rewritten RailsDiff to be an Ember app that gets its data from an API, and the API generates the diffs on the fly. This allows for things like including more versions of Rails, without having an insane impact on disk size.

You are welcome to check out the new RailsDiff: http://railsdiff.org/
I've also moved it to be in its own organization: https://github.com/railsdiff/railsdiff

**Comment by elsurudo** [comment]
Very nice!

**Comment by guilhermesimoes** [comment]
Kudos! :clap:
