### ISSUE TITLE
Missing 4.0.13 release

### ISSUE THREAD

**Issue by olivierlacan** [jswanner/RailsDiff#12]
Noticed this one was missing: http://railsdiff.org/diff/v4.0.3/v4.0.13/full/
https://rubygems.org/gems/rails/versions/4.0.13

I couldn't find instructions to generate a missing release on the README.

**Comment by jswanner** [comment]
Weird, I didn't get an email about the release 4.0.13 and 4.1.9. I've updated the site for both versions.

> I couldn't find instructions to generate a missing release on the README.

The answer is:

``` sh
$ rake
```

Although, if you've never run it before, it will probably take quite a to run; after which it doesn't take long at all to add just a version or two.
