### ISSUE TITLE
Can't modify frozen NilClass when running rake

### ISSUE THREAD

**Issue by olivierlacan** [jswanner/RailsDiff#13]
Here's what I get when I run rake:

```
$ rake
mkdir -p tmp/rails
Cloning Rails repo
Updating Rails repo
Generating: diff/v2.3.6/v2.3.7/index.html
rake aborted!
can't modify frozen NilClass
```

Idea why this happens? You don't have a specified Ruby version and I'm running this on 2.2.0p0.

**Comment by jswanner** [comment]
I hadn't yet upgraded to 2.2.0, so I hadn't encountered that error. Thanks for pointing it out.
