### ISSUE TITLE
Side-by-side view

### ISSUE THREAD

**Issue by noinkling** [jswanner/RailsDiff#14]
This is a feature request rather than an issue, but a side-by-side view (like Github implemented recently) would be a really nice option. Unfortunately I don't have the expertise to do it myself.

**Comment by jswanner** [comment]
@noinkling thanks for the suggestion. Unfortunately, I feel like this feature isn't well suited while the site is just a statically generated one, as it just increases its already large on-disk footprint that much larger. I've been thinking more and more about how we all might be better served if this site was no longer static generated, as it would allow for more features without the hard drive penalty that I or anyone else that check wanting to contribute would incur.

So, all that being said: I like your idea, but I think the site would need a major overhaul before I'd want to add it.

**Comment by jswanner** [comment]
I've completely rewritten RailsDiff to be an Ember app that gets its data from an API, and the API generates the diffs on the fly. This allows for things like adding more features to the UI, without having an insane impact on disk size. While I have not built the side-by-side view you have requested in this issue, I'm certainly much more open to the idea now with this new architecture.

You are welcome to check out the new RailsDiff: http://railsdiff.org/
I've also moved it to be in it's own organization: https://github.com/railsdiff/railsdiff

I'm closing this issue, but you may open a new one on the new repository if you so desire.
