### ISSUE TITLE
Filename should link to full file

### ISSUE THREAD

**Issue by olivierlacan** [jswanner/RailsDiff#5]
It's often useful to see the changes in context (env.rb files).

![image](https://f.cloud.github.com/assets/65950/434904/65edd4b6-af7e-11e2-89f3-c8f0b42b23fa.png)

**Comment by jswanner** [comment]
And, where do you want these links to go? The blob on GitHub for that ref?

**Comment by olivierlacan** [comment]
Good idea.

**Comment by jswanner** [comment]
While this seems a good idea, need to keep in mind these files are generated from generator templates; for instance,  the file you used, this is its template URL: https://github.com/rails/rails/blob/master/railties/lib/rails/generators/rails/app/templates/config/environments/production.rb.tt .

Linking to a template might almost be more confusing for the person looking at it. Kind of the point of RailsDiff is to compare the difference of the output of the application generator, and not to compare the diff between the template files.

Also, getting back to "where should these links go?", we're looking at a diff between 2 versions of Rails. We'd link to the blob on GitHub for which ref? The lower ref, greater ref, both?

**Comment by olivierlacan** [comment]
My original yearning as a user was to simply see the full files in order to see all the changes for each individual version in context. If its too complex to link to a GitHub repo, why not host all the generated files for each version on RailsDiff? Too many files?

**Comment by jswanner** [comment]
> My original yearning as a user was to simply see the full files in order to see all the changes for each individual version in context.

You want to see a full list of file names included in the diff? Like a nav menu (table of contents) on the side linking to each file within the page?

> If its too complex to link to a GitHub repo

It's not a matter of being complicated, but can you give me a concrete example of what you'd want it linked to?

> why not host all the generated files for each version on RailsDiff? Too many files?

As it currently stands, that's 2351 files; at about 13MB, and that's assuming we're not talking about wrapping it in HTML with syntax highlighting and such.

**Comment by olivierlacan** [comment]
See the above screenshot, `config/environments/production.rb` would link to the `production.rb` raw file (syntax highlighted or not, doesn't really matter) for the newer version of Rails — the basis for the diff.

**Comment by jswanner** [comment]
4fea80e2aebcc4191455ba6195e1d4d2b0e42913 adds another page with full file diffs, and the filenames on the short diffs link to the same file on the full file diff.
